import { Navbar } from "@/components/navbar";
import { Sidebar } from "@/components/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="grid min-h-screen grid-cols-[auto_1fr] grid-rows-[auto_1fr]">
            {/* Sidebar in the first column, spanning both rows */}
            <div className="row-span-2 border-r">
              <Sidebar />
            </div>

            {/* Navbar in the second column, first row */}
            <div>
              <Navbar />
            </div>

            {/* Main content in the second column, second row */}
            <main className="p-6">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
