# Generated by Django 5.2.1 on 2025-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='health_records/'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
